name: build

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install (npm ci)
        run: cd website && npm ci

      - name: Build
        run: cd website && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: ./website/dist
